package:
  name: "ziran"
  version: "1.0.7"

source:
  git_rev: v1.0.7
  # git_url: https://github.com/tyronechen/ziran.git
  git_url: /fs04/lz25/tyronec/repos/test/ziran
  # url: https://github.com/tyronechen/ziran/releases/download/{{ version }}/ziran-{{ version }}.tar.gz
  git_depth: 0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - create_dataset_bio = "ziran.create_dataset_bio:main"
    - create_dataset_nlp = "ziran.create_dataset_nlp:main"
    - create_embedding_bio_sp = "ziran.create_embedding_bio_sp:main"
    - create_embedding_bio_kmers = "ziran.create_embedding_bio_kmers:main"
    - cross_validate = "ziran.cross_validate:main"
    - embedding_pipeline = "ziran.embedding_pipeline:main"
    - fit_powerlaw = "ziran.fit_powerlaw:main"
    - freq_pipeline = "ziran.freq_pipeline:main"
    - generate_synthetic = "ziran.generate_synthetic:main"
    - kmerise_bio = "ziran.kmerise_bio:main"
    - parse_sp_tokens = "ziran.parse_sp_tokens:main"
    - summarise_metrics = "ziran.summarise_metrics:main"
    - sweep = "ziran.sweep:main"
    - tokenise_bio = "ziran.tokenise_bio:main"
    - train = "ziran.train:main"

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - gensim==4.2.0
    - hyperopt==0.2.7
    - matplotlib==3.5.2
    - pandas==1.4.2
    - pytorch==1.10.0
    - ray-default==1.13.0
    - scikit-learn==1.1.1
    - screed==1.0.5
    - seaborn==0.11.2
    - sentencepiece==0.1.96
    - tokenizers==0.12.1
    - tqdm==4.64.0
    - transformers==4.23.1
    - wandb==0.13.4
    - weightwatcher==0.6.4
    - xgboost==1.7.1
    - yellowbrick==1.3.post1

about:
  home: https://gitlab.com/tyagilab/ziran
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Empirical genomic data tokenisation and data-free deep-learning model evaluation."

extra:
  recipe-maintainers:
    - tyronechen
