name: Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'
  pull_request:
    branches:
      - '**'    
  workflow_dispatch: # allows you to trigger manually

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create boa build env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          use-mamba: true
          channels: conda-forge,bioconda,tyronechen,defaults
          channel-priority: true
          auto-activate-base: false
          activate-environment: boa
          environment-file: etc/build.yml
      
      - name: build genomenlp for linux (main)
        shell: bash -l {0}
        run: |
          mamba activate build
          mkdir build
          conda mambabuild -c conda-forge -c tyronechen --output-folder build src/genomenlp/

      - name: generate builds for other operating systems and push
        shell: bash -l {0}
        run: |
          mamba activate build
          USER=tyronechen
          builds=$(find build -name "genomenlp*tar.bz2")
          conda-convert ${builds} -p all -o build
          builds=$(find build -name "genomenlp*tar.bz2")
          for i in ${builds}; do anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u ${USER} ${i} --force; done
          
      - name: check if package install OK
        shell: bash -l {0}
        run: |
          mamba activate build
          sweep -h
